// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"architecture.mdx": () => import("../content/docs/architecture.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "troubleshooting.mdx": () => import("../content/docs/troubleshooting.mdx?collection=docs"), "api/aggregates.mdx": () => import("../content/docs/api/aggregates.mdx?collection=docs"), "api/ask.mdx": () => import("../content/docs/api/ask.mdx?collection=docs"), "api/authentication.mdx": () => import("../content/docs/api/authentication.mdx?collection=docs"), "api/chunks.mdx": () => import("../content/docs/api/chunks.mdx?collection=docs"), "api/client-integration.mdx": () => import("../content/docs/api/client-integration.mdx?collection=docs"), "api/discovery.mdx": () => import("../content/docs/api/discovery.mdx?collection=docs"), "api/entities.mdx": () => import("../content/docs/api/entities.mdx?collection=docs"), "api/errors.mdx": () => import("../content/docs/api/errors.mdx?collection=docs"), "api/index.mdx": () => import("../content/docs/api/index.mdx?collection=docs"), "api/ingestion.mdx": () => import("../content/docs/api/ingestion.mdx?collection=docs"), "api/jobs.mdx": () => import("../content/docs/api/jobs.mdx?collection=docs"), "api/objects.mdx": () => import("../content/docs/api/objects.mdx?collection=docs"), "api/query.mdx": () => import("../content/docs/api/query.mdx?collection=docs"), "api/videos.mdx": () => import("../content/docs/api/videos.mdx?collection=docs"), "concepts/aggregators.mdx": () => import("../content/docs/concepts/aggregators.mdx?collection=docs"), "concepts/analyzers.mdx": () => import("../content/docs/concepts/analyzers.mdx?collection=docs"), "concepts/chunking.mdx": () => import("../content/docs/concepts/chunking.mdx?collection=docs"), "concepts/glossary.mdx": () => import("../content/docs/concepts/glossary.mdx?collection=docs"), "concepts/pipeline.mdx": () => import("../content/docs/concepts/pipeline.mdx?collection=docs"), "concepts/retrieval.mdx": () => import("../content/docs/concepts/retrieval.mdx?collection=docs"), "getting-started/configuration.mdx": () => import("../content/docs/getting-started/configuration.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/quickstart.mdx": () => import("../content/docs/getting-started/quickstart.mdx?collection=docs"), "workspace/agent-chat.mdx": () => import("../content/docs/workspace/agent-chat.mdx?collection=docs"), "workspace/clips-and-artifacts.mdx": () => import("../content/docs/workspace/clips-and-artifacts.mdx?collection=docs"), "workspace/ingesting-video.mdx": () => import("../content/docs/workspace/ingesting-video.mdx?collection=docs"), "workspace/projects.mdx": () => import("../content/docs/workspace/projects.mdx?collection=docs"), "workspace/video-details.mdx": () => import("../content/docs/workspace/video-details.mdx?collection=docs"), }),
};
export default browserCollections;